name: Update ebs_pricing.json
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
      - name: do an update
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: make update
      - name: Commit
        run: |
          git config --global user.name 'GitHub Updater'
          git config --global user.email 'support@cloudkeep.io'
          git commit -am "daily update"
          git push
